name: Deploy to Production (main branch)
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

  #workflow_dispatch:
    
jobs:
  build-frontend-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
        
      - name: Build App
        run: |
          npm ci
          npm run build

      - name: Upload artifact for deployment job
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: .

  deploy-to-caprover:
    runs-on: ubuntu-latest
    needs: build-frontend-app
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: .

      - name: Listing files
        run: ls -la

      - uses: master-atul/tar-action@v1.0.2
        with:
          command: c
          cwd: ../
          files: |
            frontend/dist/
            ./backend/
            ./captain-definition
            ./Dockerfile
          outPath: deploy.tar

      - name: Deploy to production
      - uses: premoweb/deploy-to-caprover@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          branch: 'main'