name: Deploy to Production (main branch)
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:
defaults:
  run:
    working-directory: ./
    
jobs:
  build-vue3-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Git Hashes
        uses: Im-Fran/git-hashes-action@v1.0.0
        with:
          short-form: true
    
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Cache dependencies
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
        
      - name: Build frontend
        run: |
          npm run build

      - uses: actions/checkout@v2
      - uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./backend
            ./captain-definition
            ./Dockerfile
          outPath: deploy.tar
          
      - uses: premoweb/deploy-to-caprover@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          branch: 'main'

