name: Deploy to Production (main branch)
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:
defaults:
  run:
    working-directory: ./
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci 
        
      - name: Build frontend
        run: |
          npm run build

      - uses: master-atul/tar-action@v1.0.2
        with:
          command: c
          cwd: ./
          files: |
            ./dist
            ./backend
            ./captain-definition
            ./Dockerfile
          outPath: deploy.tar
          
      - uses: premoweb/deploy-to-caprover@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          branch: 'main'

