name: Deploy to Production (main branch)
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

  #workflow_dispatch:
    
jobs:
  build-frontend-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./build/
          retention-days: 1

  deploy-to-caprover:
    runs-on: ubuntu-latest
    needs: build-frontend-app

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact from `build-frontend-app`
        uses: actions/download-artifact@v3
        with:
          path: ./build/

      - name: Listing files
      - run: |
          ls -la

      - name: Package front-end and backend-end apps together.
      - uses: master-atul/tar-action@v1.0.2
        with:
          command: c
          cwd: ../
          files: |
            ./artifact/
            ./backend/
            ./captain-definition
            ./Dockerfile
          outPath: deploy.tar

      - name: Deploy to production
      - uses: premoweb/deploy-to-caprover@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          branch: 'main'
