name: Deploy to Production (main branch)
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci 
        
      - name: Build App
        run: |
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        id: upload-artifact
        with:
          name: build
          path: ./build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build/

      - name: Add build directory to repository
        run: |
          mkdir -p build
          cp -r build/* .

      - uses: master-atul/tar-action@v1.0.2
        with:
          command: c
          cwd: ./
          files: |
            ./build
            ./backend/
            ./captain-definition
            ./Dockerfile
          outPath: deploy.tar

      - name: Deploy to production
      - uses: premoweb/deploy-to-caprover@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          branch: 'main'